openapi: 3.0.3
info:
  title: MyPersonalDriver A&A - OpenAPI 3.0
  description: Authentication and authorization 
  termsOfService: terms
  contact:
    email: MyPersonalDriver@example.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about MyPersonalDriver
  url: da_definire.com
servers:
  - url: da definire
tags:
  
  - name: user
    description: Operations about user
paths:
  /accounts/register:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by new users.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json: 
            schema:
             $ref: '#/components/schemas/register'
          application/xml:
            schema:
              $ref: '#/components/schemas/register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/register'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterSuccessfull'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterSuccessfull'
        400:
          description: client error operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterCError'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterCError'
        500:
          description: server error operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterSError'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterSError'
        
  /accounts/login:
    post:
      tags:
        - user
      summary: User logs in
      description: authenticates and creates a session token for user
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/loginBody'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseLoginSuccessfull'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponseLoginSuccessfull'
        
        '204':
          description: Failed operation wrong email/password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseLoginError'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponseLoginError'
        400:
          description: client error operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterCError'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterCError'
        500:
          description: server error operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterSError'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterSError'
        default:
          description: successful operation
        
  
  /accounts/logout:
    delete:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      parameters: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseLogoutSuccessfull'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponseLogoutSuccessfull'
        
        '204':
          description: Failed logout Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseLogoutError'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponseLogoutError'
        400:
          description: client error operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterCError'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterCError'
        500:
          description: server error operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterSError'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponseRegisterSError'
        default:
          description: successful operation
 
components:

    
  schemas:
    loginBody:
      type: object
      properties:
        email:
          type: string
          example: example@email.com
        password:
          type: string
          format: string
          example: Password1!!
    
    register:
      type: object
      properties:
        email:
          type: string
          example: john@email.com
        
        password:
          type: string
          example: 'Password1'
        
        role:
          type: string
          example: 'driver'
        
        firstName:
          type: string
          example: 'Idri'
        lastName:
          type: string
          example: 'Hoxha'
        dateOfBirth:
          type: object
          example: '20/04/2000'
        
    ApiResponseLoginSuccessfull:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
          example: "logged in successfully"
        body:
          type: string
          example: {
            SessionToken: "asfasdgfdgcdvlkl"
          }
      xml:
        name: '##default'
      
    ApiResponseLoginError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
          example: "Retry Login"
      xml:
          name: '##default'
    
    ApiResponseRegisterSuccessfull:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
          example: "registred successfully"
      xml:
        name: '##default'
    
    ApiResponseRegisterCError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
          example: "Error on client side"
      xml:
        name: '##default'
    ApiResponseRegisterSError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
          example: "Error on server side"
      xml:
        name: '##default'
    ApiResponseLogoutSuccessfull:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
          example: "You have logged out"
      xml:
        name: '##default'
    ApiResponseLogoutError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
          example: "You are already logged out"
      xml:
        name: '##default'