openapi: 3.0.3
info:
  title: Reports
  description: |-
    Questa funzionalità ci permette di inoltrare una segnalazione qualora lo si ritenga necessario. Potremo inviare vari tipi di segnalazione a seconda del problema rilevato.
    
  #termsOfService: http://swagger.io/terms/
  #contact:
    #email: apiteam@swagger.io
  #license:
    #name: Apache 2.0
    #url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
  
#externalDocs:
  #description: Find out more about Swagger
  #url: http://swagger.io
  
servers:
  - url: https://localhost/reports
  
tags:
  - name: Reports
    description: Segnala un problema
    
paths:
  /users/{userId}/rides/{rideId}/reports/add:
    post:
      tags:
        - reports
      summary: Inserisci una nuova segnalazione
      description: Inserisci una nuova segnalazione relativa ad una determinata corsa
      operationId: addReport
      parameters:
        - name: userId
          in: path
          description: UserId che vuole inviare la segnalazione
          required: true
          schema:
            type: integer
            format: int64
        - name: rideId
          in: path
          description: rideId della corsa relativa alla segnalazione
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: ID not found
        '422':
          description: Validation exception
          
  /rides/{rideId}/reports/{reportId}/modify:
    put:
      tags:
        - reports
      summary: Modifica segnalazione
      description: Modifica una segnalazione esistente relativa ad una determinata corsa
      operationId: updateReport
      parameters:
        - name: rideId
          in: path
          description: rideId relativo alla segnalazione
          required: true
          schema:
            type: integer
            format: int64
        - name: reportId
          in: path
          description: reportId relativo alla segnalazione
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: ID not found
        '422':
          description: Validation exception
          
  /rides/{rideId}/reports/{reportId}/delete:
    delete:
      tags:
        - reports
      summary: Elimina segnalazione
      description: Elimina una segnalazione esistente relativa ad una determinata corsa
      operationId: deleteReport
      parameters:
        - name: rideId
          in: path
          description: rideId relativo alla segnalazione
          required: true
          schema:
            type: integer
            format: int64
        - name: reportId
          in: path
          description: reportId relativo alla segnalazione
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: ID not found
        '422':
          description: Validation exception
          
  /users/{userId}/reports/view:
    get:
      tags:
        - reports
      summary: Visualizza le segnalazioni presenti
      description: Visualizza le segnalazioni presenti
      operationId: printReports
      parameters:
        - name: userId
          in: path
          description: UserId che ha inviato le segnalazioni
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: ID not found
        '422':
          description: Validation exception
    