openapi: 3.0.3
info:
  title: MyPersonalDriver A&A - OpenAPI 3.0
  description: Authentication and authorization 
  termsOfService: terms
  contact:
    email: MyPersonalDriver@example.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about MyPersonalDriver
  url: da_definire.com
servers:
  - url: da definire
tags:
  
  - name: user
    description: Operations about user
paths:
  /accounts/register:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by new users.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json: 
            schema:
             $ref: '#/components/schemas/register'
          application/xml:
            schema:
              $ref: '#/components/schemas/register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/register'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /accounts/login:
    post:
      tags:
        - user
      summary: User logs in
      description: authenticates and creates a session for user
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/loginBody'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        default:
          description: successful operation
  
  /accounts/logout:
    delete:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      parameters: []
      responses:
        default:
          description: successful operation
 
components:

    
  schemas:
    loginBody:
      type: object
      properties:
        email:
          type: string
          example: example@email.com
        password:
          type: string
          format: string
          example: Password1!!
    
    register:
      type: object
      properties:
        email:
          type: string
          example: john@email.com
        
        password:
          type: string
          example: 'Password1'
        
        role:
          type: string
          example: 'driver'
        
        firstName:
          type: string
          example: 'Idri'
        lastName:
          type: string
          example: 'Hoxha'
        dateOfBirth:
          type: object
          example: '20/04/2000'
        
      xml:
        name: register
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  
    api_key:
      type: apiKey
      name: api_key
      in: header